# This is a workflow that is manually triggered to test the docker build

name: Manual workflow for docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check runner
        run: echo "Starting CI build..."

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show files
        run: ls -la

      - name: Create the .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Check .env contents
        run: cat .env

      - name: Install dependencies
        run: npm install

      - name: Docker Compose Build & Up
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose-deploy.yml"
